export const DURUM_TIPLERI = {
  BEKLEMEDE: 'BEKLEMEDE',
  DEVAM_EDIYOR: 'DEVAM_EDIYOR',
  TAMAMLANDI: 'TAMAMLANDI',
  IPTAL: 'IPTAL'
};

export const ONCELIK_SEVIYELERI = {
  DUSUK: 'DUSUK',
  ORTA: 'ORTA',
  YUKSEK: 'YUKSEK',
  KRITIK: 'KRITIK'
};

export const EKSIKLIK_KATEGORILERI = {
  YAPI: 'YAPI',
  ELEKTRIK: 'ELEKTRIK',
  MEKANIK: 'MEKANIK',
  INCE_ISLER: 'INCE_ISLER',
  PEYZAJ: 'PEYZAJ',
  DIGER: 'DIGER'
};
